alert("25")
	document.write(1+1);
	document.write("<br>");
	var name,age,roll_num,roll;
	name="Sanjida Samanta";
	age=19;
	roll_num="BFH2025010F";
	roll="1234.23";
	document.write("Name :"+name);
	document.write("<br>");
	document.write("Age :"+age);
	document.write("<br>");
	document.write("Roll :"+roll_num);
	document.write("<br>");
	document.write(typeof(roll_num));
	document.write("<br>");
	age=19;
	document.write(typeof(toString(age)));
	document.write("<br>");
	document.write(parseInt(roll));
	document.write("<br>");
	document.write(parseFloat(roll));